tpl_frontend:
    resource: "@TplFrontendBundle/Resources/config/routing.yml"
    prefix:   /

announce:
    resource: "@AnnounceBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /
    
address:
    resource: "@AddressBundle/Resources/config/routing.yml"
    prefix:   /    
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
